Guidelime.registerGuide([[
[NDemo 1 - 6 Dun Morogh][GADwarf,Gnome]
At the NPC in front of you [L30,71Dun Morogh] get [QP179Dwarven Outfitters]
Kill wolves south of you for [QC179]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3109Encrypted Rune] and [QP233Coldridge Valley Mail Delivery][ARogue,Dwarf]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3113Encrypted Memorandum] and [QP233Coldridge Valley Mail Delivery][ARogue,Gnome]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3106Simple Rune] and [QP233Coldridge Valley Mail Delivery][AWarrior,Dwarf]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3112Simple Memorandum] and [QP233Coldridge Valley Mail Delivery][AWarrior,Gnome]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3115Tainted Memorandum] and [QP233Coldridge Valley Mail Delivery][AWarlock]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3107Consecrated Rune] and [QP233Coldridge Valley Mail Delivery][APaladin]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3108Etched Rune] and [QP233Coldridge Valley Mail Delivery][AHunter]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3110Hallowed Rune] and [QP233Coldridge Valley Mail Delivery][APriest]
Return to the NPC [L30,71], turn in [QT179], and accept [QP3114Glyphic Memorandum] and [QP233Coldridge Valley Mail Delivery][AMage]
Left of you accept [QP170A New Threat]
Kill troggs along your way for [QC170][O]
At the camp to the west [L22,71] turn in [QT233] and accept [QP234Coldridge Valley Mail Delivery] and [QP183The Boar Hunter]
Kill boars in the surrounding area and return to the camp [L22,71] where you turn in [QT183The Boar Hunter]
Go to the next camp SE along the path [L25,76], turn in [QT234], and accept [QP182The Troll Cave]
Kill trolls in the area for [QC182][O]
As soon as you are level [XP4] go back to [L25,76] and accept [QP3364Scalding Mornbrew Delivery]
[H] Hearth back and enter Anvilmar. Accept [QP3361A Refugee's Quandary] [L29,68]
Further north [L29,66] turn in [QT3364] and accept [QP3365Bring Back the Mug]
[T] Get new skills at your trainer and turn in [QT3109][ARogue,Dwarf]
[T] Get new skills at your trainer and turn in [QT3113][ARogue,Gnome]
[T] Get new skills at your trainer and turn in [QT3106][AWarrior,Dwarf]
[T] Get new skills at your trainer and turn in [QT3112][AWarrior,Gnome]
[T] Get new skills at your trainer and turn in [QT3107][APaladin]
[T] Get new skills at your trainer and turn in [QT3108][AHunter]
[T] Get new skills at your trainer and turn in [QT3110][APriest]
[T] Get new skills at your trainer and turn in [QT3114][AMage]
[T] Get new skills at your trainer, turn in [QT3115], and accept [QP1599Beginnings][AWarlock]
Exit Anvilmar and finish [QC170]
Turn in [QT170] at the starting point [L30,71]
Turn in [QT3365] at the camp at the end of the road [L25,76]
Loot the three items for [QC3361] at the three troll camps (box at [L21,76], chest at [L23,80], and bucket at [L26,79])
At the camps or in the cave finish [QC182]
Go back to the camp at [L25,76], turn in [QT182], and accept [QP218The Stolen Journal]
In the troll cave keep left until you find and kill Grik'nir the Cold for [QC218The Stolen Journal][AWarrior,Mage,Hunter,Rogue,Priest,Paladin]
Kill novices in the southern half of the cave until you finish [QC1599][AWarlock]
At the end of the cave kill Grik'nir the Cold for [QC218The Stolen Journal][AWarlock]
Turn in [QT218] at the dwarf camp [L25,76] and accept [QP282Senir's Observations]
[H] Hearth or die to get back and turn in [QT3361] in Anvilmar
Exit Anvilmar and follow the path east and turn in [QT282] and accept [QP420Senir's Observations]
To your right accept [QP2160Supplies to Tannok]
Leave the area through Coldridge Pass
]],...)