Guidelime.registerGuide([[
[DL20-60 https://www.curseforge.com/wow/addons/guidelime_shiku Guidelime_Shiku]
[N 20-20 Warlock Class Quest]
[GA Warlock]
[D Level 20 Class Quest for Alliance and Horde Warlocks]
Make your way to Ironforge[A Gnome]
[G47.6,9.6Ironforge]Accept[QA1717][A Gnome]
Head to the deeprun tram and go to Stormwind, alternatively you can take a flight path[A Gnome]
[G25.2,78.6Stormwind City]Turn in[QT1717]in the Slaughtered Lamb in the Mage District[A Gnome]
Make your way to Stormwind[A Human]
[G25.2,78.6Stormwind City]Accept[QA1716]
Fly to Menethil Harbor if you have the flight path, otherwise fly to Thelsamar Dun Morogh[A Alliance]
The next few steps labeled 'MH' will describe how to get to Menethil Harbor if you didn't have the flight path[A Alliance]
MH - Run North out of Thelsamar towards the Wetlands, run through the tunnel. \\ On the other side, jump off the cliff into wetlands to Suicide.[A Alliance]
MH - Spirit rez in the Wetlands[A Alliance]
MH - Run west along the road until you reach Menethil Harbor.[A Alliance]
MH - [G9.4,59.6Wetlands]Grab the flightpath[A Alliance]
Take the boat to Auberdine[A Alliance]
[G36.4,45.4Darkshore]Grab the Flightpath if you don't have it for whatever reason[A Alliance]
Fly to Ratchet if you have, if not fly to Astranaar, \\ [G34.4,48.0Ashenvale] if not Run south into Ashenvale and grab the flightpath[A Alliance]
Ride along the road south into The Barrens.[A Alliance]
[G63,37The Barrens]Stop at the Ratchet flightpath if you don't have it yet.[A Alliance]
[G49.2,57The Barrens]Head here, MAKE SURE YOU RUN AROUND CROSSROADS![A Alliance]
Turn in[QT1716][A Alliance]
Accept[QA1738][A Alliance] 
[G63,37The Barrens]Go to the flight path in Ratchet and Fly to Astranaar in Ashenvale[A Alliance]
[G31,31Ashenvale]Clear the area and loot the Heartswood[QC1738][A Alliance]
Head back to Stormwind, either  hearth or take the boat back to Menethil Harbor and fly to Stormwind[A Alliance]
[G25.2,78.6Stormwind City]Turn in[QT1738][A Alliance]
Accept[QA1739][A Alliance]
Go to the Summoning circle from where you did the Void Walker Quest and summon/kill the succubus[QC1739][A Alliance]
Go back to Gakin and turn in[QT1739][A Alliance]
[G48.2,45.6Orgrimmar]Accept[QA1507]From the Cleft of Shadows[A Orc]
Turn in[QT1507] A few steps away[A Orc]
Accept[QA1508][A Orc]
[G37.2,59.6]Turn in[QT1508][A Orc]
Accept[QA1509][A Orc]
[G51.8,30.2The Barrens]Fly to the Crossroads and turn in[QT1509][A Orc]
Accept[QA1510][A Orc]
[G39,29]Head to this spot, head west to exactly where 'Stonetalon Mountains' pops up on the screen, then STOP[A Orc]
[G73,95Stonetalon Mountains]There is a path up the mountain on the left. Follow the path and turn in[QT1510][A Orc]
Accept[QA1511][A Orc]
[G44.6,59.2The Barrens]Head back to The Barrens and turn in[QT1511][A Orc]
Accept[QA1515][A Orc]
[G43.2,47.8]Turn in[QT1515][A Orc]
Accept[QA1512][A Orc]
[G48.2,45.6Orgrimmar]Fly back to Orgrimmar and turn in [QT1512][A Orc]
Accept[QA1513][A Orc]
Summon the Succubus, fight her and subdue her[A Orc]
[G48.2,45.6]Turn in[QT1513][A Orc]
Grats you can summon a hot grill!

]],"Class Quests- by Shikushiku")
