Guidelime.registerGuide([[
[DL1-60 https://www.curseforge.com/wow/addons/guidelime_tugs GuideLime_TUGs]
[GA Alliance]
[N1-9Human TUGs Leveling Guide]
[NX9-11 Dun Morogh, Loch Modan]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
If you use this guide alone or less than 5 man doing the elite quests/dungeon grind might be too hard/impossible, just skip that and continue with the guide,it does have enough quests to get you to 60 either way!!!
Accept: [QA783]
TurnIn: [QT783]
Accept: [QA7]
Accept: [QA5261]
TurnIn: [QT5261]
Accept: [QA33]
Do: [QC33]
TurnIn: [QT33]
Accept: [QA18]
Do: [QC18]
TurnIn: [QT18]
Accept: [QA3903]
Accept: [QA6]
TurnIn: [QT3903]
Accept: [QA3904]
Do [QC3904- ][QC6 Bounty on Garrick Padfoot and Milly's Harvest]
TurnIn: [QT3904]
Accept: [QA3905]
Do: [QC7]
TurnIn: [QT6]
TurnIn: [QT7]
Accept: [QA3100][A Warrior]
Accept: [QA15]
TurnIn: [QT3100][A Warrior]
TurnIn: [QT3905]
Do: [QC15]
TurnIn: [QT15]
Accept: [QA2158]
Accept: [QA60]
Set your [H] to Elwynn Forest at [G43.8,65.8Elwynn Forest]
TurnIn: [QT2158]
Accept: [QA62]
Accept: [QA47]
Kill all Boars(especially good on the fields you will go to) for 4x Chunk of Boar Meat
Accept: [QA106]
Accept: [QA85]
TurnIn: [QT106]
Accept: [QA111]
TurnIn: [QT111]
Accept: [QA107]
TurnIn: [QT85]
Accept: [QA86]
TurnIn: [QT86]
Accept: [QA88]
Accept: [QA84]
TurnIn: [QT84]
Accept: [QA87]
Do [QC62- ][QC47- ][QC60- ][QC87 Kobold Candles,The Fargodeep Mine,Gold Dust Exchange,GoldTooth]
TurnIn: [QT47]
TurnIn: [QT62]
Accept: [QA76]
TurnIn: [QT107]
TurnIn: [QT60]
Accept: [QA61]
Accept: [QA112]
[GA Warrior]Buy Gladius
Do: [QC112]
Do: [QC76]
Die and rezz at Ghosthealer
TurnIn: [QT112]
Accept: [QA114]
Buy 2x6Slot Bags
TurnIn: [QT76]
Accept: [QA40]
TurnIn: [QT40]
Accept: [QA35]
Do: [QC88]
TurnIn: [QT35]
Accept: [QA37]
Accept: [QA52]
TurnIn: [QT37]
Accept: [QA45]
Accept: [QA5545]
Do [QC5545- ][QC52 Protect the Frontier,A Bundle of Trouble]
TurnIn: [QT45]
Accept: [QA71]
TurnIn: [QT5545]
TurnIn: [QT52]
TurnIn: [QT71]
Accept: [QA39]
Use your [H] Hearthstone.
TurnIn: [QT114]
TurnIn: [QT88]
TurnIn: [QT87]
TurnIn: [QT39]
Accept: [QA1097]
TurnIn: [QT61]
TurnIn: [QT1097]
Accept: [QA353]
Take the Tram to Ironforge
Get the [P] flightpath at: [G55.5,47.8Ironforge]

]],"TUGs The Ultimate (Leveling) Guides")
