Guidelime.registerGuide([[
[DL1-60 https://www.curseforge.com/wow/addons/guidelime_markymark Guidelime_MarkyMark]
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Dwarf,Gnome]
[N5-12 Dun Morogh/Loch Modan]
[NX12-16 Darkshore]
Turn in [QT420 Senir's Observations]
Accept [QA384 Beer Basted Boar Ribs]
Turn in [QT2160 Supplies to Tannok]
Set your hearth to [S Kharanos]
Accept [QA400 Tools for Steelgrill]
Accept [QA317 Stocking Jetsteam]
Accept [QA313 The Grizzled Den]
Turn in [QT400 Tools for Steelgrill]
Accept [QA5541 Ammo for Rumbleshot]
Do [QC317 Stocking Jetsteam]
Turn in [QT317 Stocking Jetsteam]
Accept [QA318 Evershine]
Do [QC313 The Grizzled Den]
Do [QC5541 Ammo for Rumbleshot]
Turn in [QT5541 Ammo for Rumbleshot]
Accept [QA312 Tundra MacGrann's Stolen Stash]
Do [QC312 Tundra MacGrann's Stolen Stash]
Turn in [QT312 Tundra MacGrann's Stolen Stash]
Turn in [QT318 Evershine]
Accept [QA319 A Favor for Evershine]
Accept [QA315 The Perfect Stout]
Accept [QA310 Bitter Rivals]
Do [QC319 A Favor for Evershine]
Turn in [QT319 A Favor for Evershine]
Accept [QA320 Return to Bellowfiz]
Run to[OC] the island in the middle of the lake to the east, die on purpose
Spirit res in Kharanos
Accept [QA287 Frostmane Hold]
[T Train] new abilities
Run inside the inn, [V buy] 1 [QC384,2 Rhapsody Malt] and 1 Thunder Ale
Run downstairs and click the [QC403 Guarded Thunderbrew Barrel]
Turn in [QT308 Distracting Jarven]
Click the barrel that appears, turn in [QT310 Bitter Rivals]
Accept [QA311 Return to Marleth]
Turn in [QT384 Beer Basted Boar Ribs], across the road accept [QA415 Rejold's New Brew]
Turn in [QT320 Return to Bellowfiz]
Turn in [QT313 The Grizzled Den]
Accept [QA412 Operation Recombobulation]
Do [QC315 The Perfect Stout]
Turn in [QT315 The Perfect Stout] & [QT415 Rejold's New Brew], accept [QA413 Shimmer Stout]
Turn in [QT311 Return to Marleth]
Do [QC412 Operation Recombobulation]
Do [QC287 Frostmane Hold]
Hearth to [H Kharanos]
Turn in [QT287 Frostmane Hold]
Accept [QA291 The Reports]
Turn in [QT412 Operation Recombobulation]
Accept [QA314 Protecting the Herd]
Do [QC314 Protecting the Herd]
Turn in [QT314 Protecting the Herd]
Accept [QA433 The Public Servant]
Accept [QA432 Those Blasted Troggs!]
Do [QC433 The Public Servant] and [QC432 Those Blasted Troggs!]
Turn in [QT433 The Public Servant]
Turn in [QT432 Those Blasted Troggs!]
Turn in [QT413 Shimmer Stout]
Accept [QA414 Stout to Kadrell]
Accept [QA224 In Defense of the King's Lands]
Accept [QA267 The Trogg Threat]
Do [QC224 In Defense of the King's Lands] & [QC267 The Trogg Threat]
Turn in [QT224 In Defense of the King's Lands] & [QT267 The Trogg Threat]
Accept [QA237 In Defense of the King's Lands Part 2]
Turn in [QT414 Stout to Kadrell]
Accept [QA1339 Mountaineer Stormpikes Task]
Accept [QA416 Rat Catching]
Set your Hearth to [S Thelsamar]
Accept [QA418 Thelsamar Blood Sausages]
Accept [QA6387 Honor Students]
Turn in [QT6387 Honor Students]
Accept [QA6391 Ride to Ironforge]
Turn in [QT1339 Mountaineer Stormpike's Task]
Accept [QA1338 Stormpike's Order]
Accept [QA307 Filthy Paws]
Do [QC416 Rat Catching] & [QC307 Filthy Paws] 
Finish [QC418 Thelsamar Blood Sausages]
Turn in [QT307 Filthy Paws]
Accept [QA419 The Lost Pilot]
Turn in [QT419 The Lost Pilot]
Accept [QA417 A Pilot's Revenge]
Do [QC417 A Pilot's Revenge]
Turn in [QT417 A Pilot's Revenge]
Run back to Loch Modan - Once the zone changes over, use auto-unstuck to die and spirit res in Thelsamar
Turn in [QT418 Thelsamar Blood Sausages]
Turn in [QT416 Rat Catching]
Fly to [F Ironforge]
Turn in [QT6391 Ride to Ironforge], accept [QA6388 Gryth Thurden]
Turn in [QT6388 Gryth Thurden]
Accept [QA6392 Return to Brock]
Hearth to [H Thelsamar]
Turn in [QT6392 Return to Brock]
Fly to [F Ironforge]
[T Train] Cooking, skill it up to 10+
Go to the bag [V vendor] in Ironforge at [G37,76] & [V buy] bags if you don't have full bags yet
Set your Hearth to [S Ironforge]
[T Train] class abilities
Run to[OC] [G31,34] in Dun Morogh. Walk up the mountain, die in the correct spot & spirit res in Menethil Harbor
Get the [P]FP
Take the boat to Darkshore

]],"MarkyMark")
