Guidelime.registerGuide([[
[DL1-60 https://www.curseforge.com/wow/addons/guidelime_markymark Guidelime_MarkyMark]
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N1-5 Elwynn Forest]
[NX5-10 Elwynn Forest]
Accept [QA783 A Threat Within]
Turn in [QT783 A Threat Within]
Accept [QA7 Kobold Camp Cleanup]
Accept [QA5261 Eagan Peltskinner] back outside
Turn in [QT5261 Eagan Peltskinner]
Accept [QA33 Wolves Across the Border]
Do [QC7 Kobold Camp Cleanup]
Turn in [QT7 Kobold Camp Cleanup] & accept [QA15 Investigate Echo Ridge]
Accept [QA18 Brotherhood of Thieves]
Do [QC33 Wolves Across the Border]
Do [QC18 Brotherhood of Thieves]
Turn in [QT18 Brotherhood of Thieves]
Accept [QA3903 Milly Osworth] & [QA6 Bounty on Garrick Padfoot]
Turn in [QT33 Wolves Across the Border]
Turn in [QT3903 Milly Osworth] & accept [QA3904 Milly's Harvest]
Do [QC3904 Milly's Harvest] & [QC6 Bounty on Garrick Padfoot]
Do [QC15 Investigate Echo Ridge]
Turn in [QT3904 Milly's Harvest] & accept [QA3905 Grape Manifest]
Turn in [QT6 Bounty on Garrick Padfoot]
Turn in [QT15 Investigate Echo Ridge] & accept [QA21 Skirmish at Echo Ridge]
Do [QC21 Skirmish at Echo Ridge]
[H]Hearth
Turn in [QT21 Skirmish at Echo Ridge]
Accept [QA54 Report to Goldshire]
Turn in [QT3905 Grape Manifest]
Accept [QA2158 Rest and Relaxation]
Turn in [QT2158 Rest and Relaxation] inside the inn
Set your Hearth to [S Goldshire]
[T Train] First Aid upstairs
Accept [QA60 Kobold Candles]
Turn in [QT54 Report to Goldshire]
Accept [QA62 The Fargodeep Mine]
Accept [QA47 Gold Dust Exchange]

]],"MarkyMark")
