Guidelime.registerGuide([[
[DL1-60 https://www.curseforge.com/wow/addons/guidelime_markymark Guidelime_MarkyMark]
[D*MarkyMark*'s 1-60 guide\\https://www.twitch.tv/darealmarkymark\\(best suited for a group of at least 2, if not 3+)]
[GA Alliance]
[N5-10 Elwynn Forest]
[NX10-12 Dun Morogh/Loch Modan]
Accept [QA85 Lost Necklace]
Accept [QA106 Young Lovers]
Turn in [QT85 Lost Necklace], accept [QA86 Pie for Billy]
Do [QC86 Pie for Billy]
Turn in [QT86 Pie for Billy] & accept [QA84 Back to Billy]
Turn in [QT106 Young Lovers] near the river & accept [QA111 Speak with Gramma]
Turn in [QT111 Speak with Gramma] & accept [QA107 Note to William]
Turn in [QT84 Back to Billy], accept [QA87 Goldtooth]
Do "[QC87,1 Goldtooth], [QC60 Kobold Candles], [QC47 Gold Dust Exchange] & [QC62 The Fargodeep Mine]
Turn in [QT87 Goldtooth]
Accept [QA88 Princess Must Die]
Use auto unstuck and spirit res in Goldshire
Turn in [QT60 Kobold Candles] & [QT107 Note to William]
Accept [QA61 Shipment to Stormwind] & [QA112 Collecting Kelp]
Turn in [QT47 Gold Dust Exchange], accept [QA40 A Fishy Peril]
Turn in [QT40 A Fishy Peril] & [QT62 The Fargodeep Mine]
Accept [QA35 Further Concerns] & [QA76 The Jasperlode Mine]
[V Buy] new weapons from the [V vendor]
Do [QC112 Collecting Kelp]
Do [QC76 The Jasperlode Mine]
Turn in [QT35 Further Concerns] [G74,71Elwynn Forest]
Accept [QA37 Find the Lost Guards] & [QA52 Protect the Frontier]
Accept [QA5545 A Bundle of Trouble]
Turn in [QT37 Find the Lost Guards] [G72,60Elwynn Forest]
Accept [QA45 Discover Rolf's Fate]
Turn in [QT45 Discover Rolf's Fate] & accept [QA71 Report to Thomas] [G80,55.6Elwynn Forest]
Do [QC52 Protect the Frontier] & [QC5545 A Bundle of Trouble]
Turn in [QT5545 A Bundle of Trouble]
Turn in [QT71 Report to Thomas] & [QT52 Protect the Frontier], accept [QA39 Deliver Thomas' Report] [G74,71Elwynn Forest]
Do [QC88 Princess Must Die!]
Turn in [QT112 Collecting Kelp]
Accept [QA114 The Escape]
Turn in [QT39 Deliver Thomas' Report] & [QT76 The Jasperlode Mine]
Accept [QA239 Westbrook Garrison Needs Help]
Accept [QA1097 Elmore's Task]
Turn in [QT114 The Escape] [G43,89Elwynn Forest]
Turn in [QT88 Princess Must Die!]
Turn in [QT239 Westbrook Garrison Needs Help], accept [QA11 Riverpaw Gnoll Bounty] [G24,74Elwynn Forest]
Accept [QA176 Wanted: Hogger]
Do [QC176 Wanted: Hogger] & [QC11 Riverpaw Gnoll Bounty]
Make sure you're 1,895 XP (1,295 if you got Furlbrow's Deed quest) or less away from level [XP 10], if not then grind to it
Turn in [QT11 Riverpaw Gnoll Bounty]
Turn in [QT184 Furlbrow's Deed] if looted, accept [QA36 Westfall Stew] [G60,19 Westfall]
Turn in [QT36 Westfall Stew]
Turn in [QT109 Report to Gryan Stoutmantle] [G56,47 Westfall]
Accept [QA6181 A Swift Message]
Turn in [QT6181 A Swift Message], accept [QA6281 Continue to Stormwind]
Get the [P]FP
Hearth to [H Goldshire]
Turn in [QT176 Wanted: Hogger]
Turn in [QT61 Shipment to Stormwind]
Turn in [QT6281 Continue to Stormwind], accept [QA6261 Dungar Longdrink]
Turn in [QT6261 Dungar Longdrink], accept [QA6285 Return to Lewis]
Fly to [F Westfall]
Turn in [QT6285 Return to Lewis]
Fly to [F Stormwind]
[V Buy] weapon [T skills] & new weapons
Turn in [QT1097 Elmore's Task]
Accept [QA353 Stormpike's Delivery]
Take the tram to Ironforge
Accept [QA6661 Deeprun Rat Roundup]
Do [QC6661 Deeprun Rat Roundup]
Turn in [QT6661 Deeprun Rat Roundup]
Get the [P]FP
Set your Hearth to [S Ironforge]
Grind to Amberstill Ranch in Dun Morogh

]],"MarkyMark")
