Guidelime.guides["Demo"] = {
	minLevel = 1,
	maxLevel = 6,
	colorQuest = "|cFF59C4F1",
	race = {"Dwarf", "Gnome"},
	steps = {
		{text = "At the NPC in front of you [L30,71Dun Morogh] get [QP179Dwarven Outfitters]"},
		{text = "Kill wolves south of you for [QC179]"},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3109Encrypted Rune] and [QP233Coldridge Valley Mail Delivery]", class = {"Rogue"}, race = {"Dwarf"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3113Encrypted Memorandom] and [QP233Coldridge Valley Mail Delivery]", class = {"Rogue"}, race = {"Gnome"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3106Simple Rune] and [QP233Coldridge Valley Mail Delivery]", class = {"Warrior"}, race = {"Dwarf"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3112Simple Memorandom] and [QP233Coldridge Valley Mail Delivery]", class = {"Warrior"}, race = {"Gnome"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3115Tainted Memorandom] and [QP233Coldridge Valley Mail Delivery]", class = {"Warlock"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3107Consecrated Rune] and [QP233Coldridge Valley Mail Delivery]", class = {"Paladin"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3108Etched Rune] and [QP233Coldridge Valley Mail Delivery]", class = {"Hunter"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3110Hallowed Rune] and [QP233Coldridge Valley Mail Delivery]", class = {"Priest"}},
		{text = "Return to the NPC [L30,71], turn in [QT179], and accept [QP3114Glyphic Memorandum] and [QP233Coldridge Valley Mail Delivery]", class = {"Mage"}},
		{text = "Left of you accept [QP170A New Threat]"},
		{text = "Kill troggs along your way for [QC170]", required = false},
		{text = "At the camp to the west [L22,71] turn in [QT233] and accept [QP234Coldridge Valley Mail Delivery] and [QP183The Boar Hunter]"},
		{text = "Kill boars in the surrounding area and return to the camp [L22,71] where you turn in [QT183The Boar Hunter]"},
		{text = "Go to the next camp SE along the path [L25,76], turn in [QT234], and accept [QP182The Troll Cave]"},
		{text = "Kill trolls in the area for [QC182]", required = false},
		{text = "As soon as you are level [XP4] go back to [L25,76] and accept [QP3364Scalding Mornbrew Delivery]"},
		{text = "[H Hearth] back and enter Anvilmar. Accept [QP3361A Refugee's Quandary] [L29,68]"},
		{text = "Further north [L29,66] turn in [QT3364] and accept [QP3365Bring Back the Mug]"},
		{text = "[T Get new skills] at your trainer and turn in [QT3109]", class = {"Rogue"}, race = {"Dwarf"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3113]", class = {"Rogue"}, race = {"Gnome"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3106]", class = {"Warrior"}, race = {"Dwarf"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3112]", class = {"Warrior"}, race = {"Gnome"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3107]", class = {"Paladin"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3108]", class = {"Hunter"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3110]", class = {"Priest"}},
		{text = "[T Get new skills] at your trainer and turn in [QT3114]", class = {"Mage"}},
		{text = "[T Get new skills] at your trainer, turn in [QT3115], and accept [QP1599Beginnings]", class = {"Warlock"}},
		{text = "Exit Anvilmar and finish [QC170]"},
		{text = "Turn in [QT170] at the starting point [L30,71]"},
		{text = "Turn in [QT3365] at the camp at the end of the road [L25,76]"},
		{text = "Loot the three items for [QC3361] at the three troll camps (box at [L21,76], chest at [L23,80], and bucket at [L26,79])"},
		{text = "At the camps or in the cave finish [QC182]"},
		{text = "Go back to the camp at [L25,76], turn in [QT182], and accept [QP218The Stolen Journal]"},
		{text = "In the troll cave keep left until you find and kill Grik'nir the Cold for [QC218The Stolen Journal]", class = {"Warrior", "Mage", "Hunter", "Rogue", "Priest", "Paladin"}},
		{text = "Kill novices in the southern half of the cave until you finish [QC1599]", class = {"Warlock"}},
		{text = "At the end of the cave kill Grik'nir the Cold for [QC218The Stolen Journal]", class = {"Warlock"}},
		{text = "Turn in [QT218] at the dwarf camp [L25,76] and accept [QP282Senir's Observations]"},
		{text = "[H Hearth] or die to get back and turn in [QT3361] in Anvilmar"},
		{text = "Exit Anvilmar and follow the path east and turn in [QT282] and accept [QP420Senir's Observations]"},
		{text = "To your right accept [QP2160Supplies to Tannok]"},
		{text = "Leave the area through Coldridge Pass"}
	}
}
