Guidelime.registerGuide(
{	
	group = "legacy",
	title = "Dun Morogh",
	source = {
		"https://legacy-wow.com/vanilla-1-60-alliance-leveling-guide/1-12-dwarf-gnomea/", 
		"https://legacy-wow.com/vanilla-1-60-alliance-leveling-guide/1-12-dwarf-gnomeb/"
	},	
	minLevel = 1,
	maxLevel = 12,	
	race = {"Dwarf", "Gnome"},	
	steps = {
		-- Part 1
		{text = "Right in front of where you start accept [QP179Dwarven Outfitters]"},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3109Encrypted Rune] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Rogue"}, race = {"Dwarf"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3113Encrypted Memorandum] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Rogue"}, race = {"Gnome"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3106Simple Rune] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Warrior"}, race = {"Dwarf"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3112Simple Memorandom] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Warrior"}, race = {"Gnome"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3115Tainted Memorandom] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Warlock"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3107Consecrated Rune] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Paladin"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3108Etched Rune] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Hunter"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3110Hallowed Rune] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Priest"}},
		{text = "Go south around [L28, 73Dun Morogh] and kill wolves for the meat then go back to [L29, 71] and turn in [QT179Dwarven Outfitters] then accept [QP3114Glyphic Memorandum] and [QP233Coldridge Valley Mail Delivery pt.1]", class = {"Mage"}},
		{text = "To your left accept [QP170A New Threat]"},
		{text = "At [L30, 74Dun Morogh] kill burly troggs and at [L26, 72] there is a camp of rockjaw troggs, kill them for [QC170A New Threat]"},
		{text = "Go back to [L29, 71] and turn in [QT170A New Threat] you should be [XP3] now"},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3109]", class = {"Rogue"}, race = {"Dwarf"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3113]", class = {"Rogue"}, race = {"Gnome"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3106]", class = {"Warrior"}, race = {"Dwarf"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3112]", class = {"Warrior"}, race = {"Gnome"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3107]", class = {"Paladin"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3108]", class = {"Hunter"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3110]", class = {"Priest"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3114]", class = {"Mage"}},
		{text = "Go in Anvilmar at [L28, 69] and turn in your classes skill npc quest [QT3115]", class = {"Warlock"}},
		{text = "Accept [QP3361A Refugee's Quandary] inside"},
		{text = "Follow the road south to [L22, 71] and turn in [QT233Coldridge Valley Mail Delivery pt.1] accept [QP234Coldridge Valley Mail Delivery pt.2] and [QP183The Boar Hunter]"},
		{text = "Just behind him start killing small boars until you have 12 for [QT183The Boar Hunter] then go back to [L22, 71] and turn it in"},
		{text = "At [L20, 76] clear the front of the tent and grab Felix's Box for [QC3361,1A Refugee's Quandary]"},
		{text = "At [L22, 80] clear in front of the tent and grab Felix's Chest for [QC3361,2A Refugee's Quandary]"},
		{text = "Run up to [L25, 75] (it’s the end of the road on the map) and turn in [QT234Coldridge Valley Mail Delivery pt.2] and accept [QP182The Troll Cave]"},
		{text = "At [L26, 79] clear in front of the cave and grab Felix's Bucket of Bolts for [QC3361,3A Refugee's Quandary] then kill the trolls in and out of it until you complete [QC182The Troll Cave]"},
		{text = "Run back up to [L25, 75] and turn in [QT182The Troll Cave] accept [QP218The Stolen Journal] you should be [XP4.8 5 or very close] to it now."},
		{text = "Go back in the cave at [L26, 79] and go left at the 3 directions to [L30, 80] and kill Grik'nir the Cold for [QC218The Stolen Journal]"},
		{text = "Return back to [L25, 75] and turn in [QT218The Stolen Journal] accept [QP282Senir's Observations pt.1]"},
		{text = "Turn around and Accept [QP3364Scalding Mornbrew Delivery] and [H hearth]."},
		{text = "Run up into Anvilmar at [L28, 69] and turn in [QT3361A Refugee's Quandary]"},
		{text = "Go further back and turn in [QT3364Scalding Mornbrew Delivery] accept [QP3365Bring Back the Mug]"},
		{text = "[T Get training] before you leave"},
		{text = "Run right to [L25, 75], everything is yellow so nothing will attack you, and turn in [QT3365Bring Back the Mug]"},
		{text = "Head toward the tunnel and turn in [QT282Senir's Observations pt.1] at [L33, 71] and accept [QP420Senir's Observations pt.2]"},
		{text = "You should be about [XP6-500 500 to 6] now"},
		{text = "About 10 feet away accept [QP2160Supplies to Tannok]"},
		{text = "Go through the tunnel and kill all the stuff on the way. Follow the road to [G46, 53] in Kharanos and kill stuff on the way until you’re [XP6]. Save your boar ribs and boar meat."},
		{text = "Once at [L46, 53] turn in [QT420Senir's Observations pt.2]"},
		{text = "Up ahead on the right, in front of the Inn, accept [QP384Beer Basted Boar Ribs]"},
		{text = "Go in the Inn and turn in [QT2160Supplies to Tannok]"},
		{text = "Go to the Innkeeper, make it your home and purchase the rhapsody malt for [QC384,2Beer Basted Boar Ribs]", manual = true},
		{text = "[T Get new skills]"},
		{text = "Go across the road from the Inn and accept [QP400Tools for Steelgrill]"},
		{text = "Go NE to [L49, 48] and accept [QP317Stocking Jetsteam] and [QP313The Grizzled Den]"},
		{text = "Go to the left house and turn in [QT400Tools for Steelgrill]"},
		{text = "By the tree out front accept [QP5541Ammo for Rumbleshot]"},
		{text = "Go to the small camp at [L44, 56] and open the box for [QC5541Ammo for Rumbleshot]"},
		{text = "From around this camp to the SW kill boars and bears until you finish [QC317Stocking Jetsteam] and [QC384Beer Basted Boar Ribs]\n" ..
				"If you’re having trouble finding boars, just go to around [L40, 65] there is a lot."},
		{text = "Go into the grizzled den at [L42, 54] and kill wendingos until you get 8 manes for [QC313The Grizzled Den]"},
		{text = "You also wanna head out to [L40, 65] and turn in [QT5541Ammo for Rumbleshot] watch the scene it’s cool, only if you aren’t time running. You should be [XP6.9 7 or very close] now"},
		{text = "[H Hearth] back to Kharanos [G47, 52]"},
		{text = "Just outside the Inn, turn in [QT384Beer Basted Boar Ribs]"},
		{text = "Go to the house at [L45, 49], NE of the Inn, and accept [QP412Operation Recombobulation]"},
		{text = "Run NE to [L49, 48] and turn in [QT317Stocking Jetsteam] accept [QP318Evershine]"},
		{text = "Turn in [QT313The Grizzled Den]"},
		{text = "You should be close to [XP7.5half way through level 7]"},
		{text = "Run west to [L30, 45] and turn in [QT318Evershine] accept [QP319A Favor for Evershine] and [QP315The Perfect Stout]"},
		{text = "Beside him accept [QP310Bitter Rivals]"},
		{text = "To the North/NE from here you’ll find tons of bears, leopards, and boars to kill for [QC319A Favor for Evershine] You should ding [XP8] while killing for this"},
		{text = "Kill troll seers and open baskets at [L41, 44] and [L41, 35] for [QC315The Perfect Stout] the drops kinda suck off the trolls but the baskets can be hard to get."},
		{text = "Die so you end up in Kharanos [G47, 52]"},
		{text = "Next to the GY accept [QP287Frostmane Hold]"},
		{text = "Go into the Inn and buy a thunder ale off the Innkeeper and down in the basement, give the ale to Jarven Thunderbrew. When he leaves touch the barrel to turn in [QT310Bitter Rivals] accept [QP311Return to Marleth]"},
		{text = "[T Get new skills]"},
		{text = "Go west to brewnall village again at [L30, 45] and turn in [QT315The Perfect Stout] and [QT319A Favor for Evershine] accept [QP320Return to Bellowfiz] and [QP413Shimmer Stout]"},
		{text = "Next to him turn in [QT311Return to Marleth] you should be [XP8.5past half way to 9] now"},
		
		-- Part 2
		{text = "Go west of brewnall and kill leper gnomes until you complete [QC412Operation Recombobulation] you should hit [XP9] getting kills"},
		{text = "Go to [L24, 50] and enter the cave kill 5 headhunters and explore the cave for [QC287Frostmane Hold] To explore it just run in and stay to the right, it will curve left and you can see a raised platform with mobs, get near it to complete exploration"},
		{text = "Die so you end up at Kharanos [G47, 52]"},
		{text = "Either straight down the steps of the Inn, or N of the GY, turn in [QT287Frostmane Hold] accept [QP291The Reports]"},
		{text = "Go NW in the house at [L45, 49] and turn in [QT412Operation Recombobulation]"},
		{text = "Go east to [L49, 48] and turn in [QT320Return to Bellowfiz] you should be [XP9.5half way to 10] now"},
		{text = "Go North to IF at [G53, 35]", completeWithNext = true, required = false},
		{text = "Make IF your home at [L21, 55Ironforge]"},
		{text = "Go to [L39, 56] in IF, behind the bank, in the kings room, turn in [QT291The Reports]"},
		{text = "Enter the tram at [G76, 51]", completeWithNext = true, required = false},
		{text = "Take the tram down to SW", completeWithNext = true, required = false},
		{text = "Go to [L66, 62Stormwind City] and get the FP"},
		{text = "Reach goldshire and enter the Inn at [G42, 65Elwynn Forest]"},
		{text = "Just to your left accept [QP60Kobold Candles]"},
		{text = "Exit the Inn and go straight out and accept [QP62The Fargodeep Mine]"},
		{text = "In the blacksmith house right here accept [QP1097Elmore's Task]"},
		{text = "Go near the carts at [L42, 67] and accept [QP47Gold Dust Exchange]"},
		{text = "Go south to the Fargodeep Mine at [L39, 82] and kill the kobolds until you complete all 3 quests [QC62The Fargodeep Mine], [QC47Gold Dust Exchange], and [QC60Kobold Candles] Make sure you go in the lower entrance so [QC62The Fargodeep Mine] is easier"},
		{text = "Once all 3 are done go to the stonefield farm just up the hill east at [L34, 84] and accept [QP85Lost Necklace] SKIP [QS88Princess Must Die!]"},
		{text = "Go east to the Maclure Vinyard at [L43, 85] and turn in [QT85Lost Necklace] accept [QC86Pie for Billy] then turn around and kill boars until it’s finished"},
		{text = "Go to [L43, 90] and accept [QP106Young Lovers]"},
		{text = "Go back west to [L34, 84] and turn in [QT86Pie for Billy] SKIP [QS84Back to Billy]"},
		{text = "Go west some to the river at [L29, 85] and turn in [QT106Young Lovers] accept [QP111Speak with Gramma]"},
		{text = "Go back to [L34, 84] and turn in [QT111Speak with Gramma] in the house, accept [QP107Note to William] You should be [XP10] now"},
		{text = "Go back to goldshire, either die or run", completeWithNext = true, required = false},
		{text = "In the Inn turn in [QT60Kobold Candles] SKIP [QS61Shipment to Stormwind] also turn in [QT107Note to William] SKIP [QS112Collecting Kelp]"},
		{text = "Straight outside the Inn, turn in [QT62The Fargodeep Mine] SKIP [QS76The Jasperlode Mine]"},
		{text = "South near the fence, turn in [QT47Gold Dust Exchange]"},
		{text = "Go up into SW to [L51, 12Stormwind City] and turn in [QT1097Elmore's Task] accept [QP353Stormpike's Delivery] this will be done on the way to the wetlands"},
		{text = "[H Hearth] to IF and [T train], do your classes lvl 10 quest"},
		{text = "Go into the tram again at [L76, 51Ironforge] accept [QT6661Deeprun Rat Roundup] just collect 5 rats and turn it in. You could skip this and keep the flute, It can really piss people off if you play it non stop around the IF bank. SKIP [QS6662Me Brother, Nipsy] unless you go back to SW on the tram because you get crap xp"},
		{text = "After this you should be [XP10.6a bit over half way to 11]"},
		{text = "Run east to [L68, 55Dun Morogh] and accept [QP433The Public Servant]"},
		{text = "Go behind him and accept [QP432Those Blasted Troggs!]"},
		{text = "Go in the pit below and kill the troggs here and in the cave for both quests then turn them in back at [L68, 55][QT433-][QT432-]"},
		{text = "Go east to [G80, 51] and follow the path into Loch Modan"},
		{text = "Go to [L22, 73Loch Modan] and accept [QP224In Defense of the King's Lands]"},
		{text = "Go up in the tower and accept [QP267The Trogg Threat]"},
		{text = "At [L33, 50] grab the FP"},
		{text = "Look for the wandering guard and accept [QP416Rat Catching]"},
		{text = "Kill troggs from [L27, 53] and north for [QC224In Defense of the King's Lands] and [QC267The Trogg Threat]"},
		{text = "Go back to [L22, 73] and turn them both in[QT224-][QT267-]"},
		{text = "Go north to the tower at [L24, 18] and turn in [QT353Stormpike's Delivery]"},
		{text = "You should be [XP12] now or close to it. You can grind if you’d like but it doesn’t matter much. Follow the Night Elf to IF guide but just go backwards. You’re going to go north through the wetlands to menethil, then boat to auberdine from here."},
	}
})