Guidelime.registerGuide(
{	
	group = "TourGuide",
	source = {
		"https://github.com/TekNoLogic/TourGuide"
	},
	minLevel = 17,	
	maxLevel = 18,
	title = "Loch Modan",
	faction = "Alliance",	
	details = "Guide from the addon TourGuide by tekkub (|cFFAAAAAAhttps://github.com/TekNoLogic/TourGuide|r)",
	steps = {
		{text = "Fly to [F Loch Modan]. Boat to Stormwind, then fly there!", race={"Dwarf", "Gnome"}, completeWithNext = true},
		{text = "Go to Loch Modan Boat to Stormwind, take the tram to IF, then run to Loch.  Make sure you grab flight points along the way.", race={"Human", "Night Elf", "Draenei"}},
		{text = "Go to Algaz Station In the north of Loch Modan.", completeWithNext = true},
		{text = "Accept [QP307Filthy Paws] Upstairs, inside the tower"},
		{text = "Accept [QP1338Stormpike's Order]"},
		{text = "Complete [QC307Filthy Paws] In the mine east of the tower"},
		{text = "Turn in [QT307Filthy Paws]"},
		{text = "Go to Thelsamar", completeWithNext = true},
		{text = "Accept [QP436Ironband's Excavation] Last house"},
		{text = "Turn in [QT414Stout to Kadrell]", required = false},
		{text = "Turn in [QT436Ironband's Excavation] Along the south shore of the loch [L64.9, 66.6Loch Modan]"},
		{text = "Accept [QP297Gathering Idols]"},
		{text = "Accept [QP298Excavation Progress Report]"},
		{text = "Complete [QC297Gathering Idols]"},
		{text = "Turn in [QT297Gathering Idols]"},
		{text = "Go to The Farstrider Lodge East of Excavation site [G83.8, 62.4]"},
		{text = "Accept [QP385Crocolisk Hunting]"},
		{text = "Accept [QP257A Hunter's Boast]"},
		{text = "Complete [QC257A Hunter's Boast]"},
		{text = "Turn in [QT257A Hunter's Boast]"},
		{text = "Accept [QP258A Hunter's Challenge]"},
		{text = "Complete [QC258A Hunter's Challenge]"},
		{text = "Turn in [QT258A Hunter's Challenge]"},
		{text = "Accept [QP271Vyrin's Revenge (Part 1)]"},
		{text = "Accept [QP2038Bingles' Missing Supplies] The NPC can be found at the easternmost shore of The Loch [L63.5, 47.9]"},
		{text = "Complete [QC385Crocolisk Hunting] Lots on the islands [L55,55] [L54,40]"},
		{text = "Complete [QC2038Bingles' Missing Supplies] The supplies are scattered around northernmost islands. Blastencapper [L54.21, 26.61], Hammer [L51.78, 24.09], Screwdriver [L48.37, 20.50], Wrench [L48.73, 30.10]"},
		{text = "Accept [QP250A Dark Threat Looms (Part 1)] Middle of the Stonewrought Dam"},
		{text = "Turn in [QT250A Dark Threat Looms (Part 1)] Barrel at the east of dam"},
		{text = "Accept [QP199A Dark Threat Looms (Part 2)]"},
		{text = "Turn in [QT199A Dark Threat Looms (Part 2)]"},
		{text = "Turn in [QT298Excavation Progress Report] Back at Thelsamar"},
		{text = "Accept [QP301Report to Ironforge]"},
		{text = "Complete [QC271Vyrin's Revenge (Part 1)] Cave top of the mountain south of Thelsamar [L39.7, 66.6]"},
		{text = "Turn in [QT385Crocolisk Hunting] Back at Farstrider Lodge"},
		{text = "Turn in [QT271Vyrin's Revenge (Part 1)]"},
		{text = "Accept [QP531Vyrin's Revenge (Part 2)]"},
		{text = "Turn in [QT531Vyrin's Revenge (Part 2)]"},
		{text = "Turn in [QT2038Bingles' Missing Supplies] Remember Bingles at the shore?"},
		{text = "Fly to [F City of Ironforge]", race={"Human", "Dwarf", "Gnome"}},
		{text = "Go to [F City of Ironforge]", race={"Night Elf", "Draenei"}},
		{text = "Grab flight point", race={"Night Elf", "Draenei"}},
		{text = "Turn in [QT301Report to Ironforge] Hall of Explorers. Skip the follow-up."}
	}
})