Guidelime.registerGuide(
[[
[N 47 - 49 Hinterlands]
[GA Alliance]
[D Made from Hakurai's Video Guide\\ https://twitch.tv/hakurai \\ Our guild is recruiting! \\ https://www.guilded.gg/KOABD]
Always grind mobs that give you xp in between locations, ALWAYS GRIND MOBS OR YOU WILL FALL BEHIND IN XP![OC]
A lot of these quests wont be possible on a F R E S H launch because of lack of AH items. The guide will still cover them for other levelers in the future, but if you can't do it, skip it, we will have to grind at certain points instead[OC]
[G53.2,60.6Stormwind City]Check the AH for 2x Elixir of Fortitude, 1x Mithril Casing,  2x Thorium Bars[OC]
[T]Train your skills
[G64,20]Turn in[QT1448]
Accept[QA1449]
Fly to [F Southshore]
This is an 8 minute, 35 second flight[OC]
Ride northeast and over the mountains behind Durnholde Keep, when you start seeing Gryphons you are in the right place.[OC]
[G14.8,44.4The Hinterlands]Accept [QA2880]
Accept [QA2877]
Navigate through the bunker, then upstairs, make this your Hearth.[OC]
Set Hearth to [H Aerie Peak]
[G12,47]All the way up the mountain, turn in[QT1449]
Accept[QA1450]
[G10,44.6]Inside the building by the flightmaster, turn in[QT1450]
Accept[QA1451]
Accept[QA2988]
[G11,46]Grab the flightpath up the ramp[OC]
Head east while hugging the northern mountain[OC]
While questing, look for at least 1 other person to help you kill an Elite for the Zulfarak Mallet[OC]
[G19,48]Go up this path up the hill[OC]
[G26,48]Turn in[QT1451]
Accept[QA1452]
While doing the next steps, keep an eye out for feathers on the ground for the quest Favored of Elune?[OC]
Clear EXCESSIVELY in the area for a zone wide quest beacon drop.[OC]
[G23,58]Click on the cage while killing trolls[QC2988,1]
Click on the second cage for [QC2988,2]
[G31,57]Click the third cage for [QC2988,3]
[G10,44.6]Turn in[QT2988]
Accept[QA2898]
If you finished Troll Necklace, you can turn that in as well, but it doesn't have to be done yet.[OC]
Try to finish [QC3661]now while clearing east, and killing wildlife for a beacon drop
[G31,60]Finish [QC2880] if you didn't yet
[G33,75]Accept [QA1446] optional sunken temple quest if you plan on doing it[OC]
[G49,69]Find someone to help you kill the elite for the ZF mallet, if you can't find anyone, you can just ride to the top and back down for [QC2989]
[G46,40]Kill Oozes for [QC2877]
The beacon should have dropped by now for [QA485]
IT IS NOT WORTH DOING THE ESCORT PART OF ALL THREE CHICKEN QUESTS UNLESS YOU CAN DO ALL OF THEM, this guide will cover them, you probably will need help for ALL THREE[OC]
[G49,38]Turn in[QT485]
Accept[QA836][OC]
Let the chicken lead the charge, it's about a 13 minute walk. [QC836]
[G80.2,60.8]Work on looting the Grog in the area for Whiskey Slim quest while doing the next objectives[OC]
There is an elite turtle named Gammerita, use the Super Snapper FX quest item at MAX RANGE to take a photo, she will aggro, just run away and reset her.[QC2944]
[G81,47]Under the waterfall, turn in the quest [QT626]
Finish looting bottles in the area for [QC580]
If you got the mallet from the elite earlier, continue to the next few steps, otherwise, hearth now.[OC]
[G58,77]You're going to have to corpse hop(run, die, go back to body, run as far as you can, die, etc) to get to the alter. Run up a stair case, then die against the wall, when you're a ghost, go to the NEXT level and ressurect there. Takes about 10 minutes of corpse hopping.[OC]
When you finally rez at the alter, quickly use the Sacred Mallet before you aggro a wolf, if you do aggro a wolf, CC it and then use the Sacred Mallet[OC]
[H]Hearth to Aerie Peak
[G14.8,44.4]Turn in[QT2880]
Turn in[QT2877]
[G10,44.6]All the way at the top turn in[QT2989]
Accept[QA2990]
[G11,46]Fly to [F Menethil Harbor]
Take the northern boat to Auberdine in Darkshore[OC]
[G36.4,45.4Darkshore]Fly to [F Rut'theran Village]
[G55.4,92Teldrassil]Turn in[QT3661]
Upstairs, turn in[QT2944]
Accept[QA2943]
[V]Clear up your bags, then fly to [F Feathermoon Stronghold]
9 minute flight, take a break![OC]
[G30.6,42.6Feralas]Accept[QA7733]
[G31.8,45.4]Turn in[QT2943]
Accept[QA2879]
Next to him, accept [QA3445]
[G44.8,43.2]Swim across and take [QA7003]
Accept[QA7721]
Head south along the coast for fuel for zapping, and use the zapper on Giants, just keep running down the shore and then back up, focusing on the giants[OC]
Complete [QC7003]
Complete [QC7721]
[G44.8,43.2]Turn in[QT7003]
Turn in[QT7721]
Start killing bears for liver, and liver from the Gorillas during the next steps, just keep an eye out for them[OC]
[G46,73]Cross the road and go cross country to the yeti area[OC]
[G51,33]This is the entrance to the yeti area, come here for the next steps[OC]
Kill yeti for the hide for [QC7733]
They also have a chance at dropping a Pristine Yeti Hide quest item, keep grinding here until you get a hide, or hit level 48[OC]
Accept [QA7735]if you got it[OC]
[G42,22]Accept [QA2844]
[G38,16]Click the flame to loot the essence
[G41,13]This is on top of the roof of the giant building, from the NORTH side of the building, use the pillar to jump onto it[OC]
[G40,9]Loot the flame
[G38,12]Far west, clear along the mountains, there is a ruined gazeebo, loot the flame
[G39,13]Run to the monolith and use Troya's staff once you're close enough to complete the quest[OC]
[QC2879]
Turn in [QT2879] at the monolith
Accept[QA2942]
[G38,10]Turn in[QT2844]
Accept[QA2845]
Loot the item on the ground to get Shay's Bell before you head off[OC]
Everytime she gets distracted, you need to target her and use the bell on her[OC]
[G42,22]Bring Shay back to Rockbiter and turn in[QT2845]
[G65,46]Accept[QA3841]
[G53.4,55.4]Accept the chicken escort if you're doing all of them [QA2767] otherwise skip this step YOU PROBABLY NEED HELP TO DO THIS QUEST[OC]
Complete the escort for [QC2767]
[G31.8,45.4]Turn in[QT1395]
[G30.6,42.6]Turn in[QT7733]
Turn in[QT7735] if you found one[OC]
If you aren't 48 yet, grind in the same areas as the previous guides to hit [XP48]
[G30.2,43.2]Fly to [F Theramore]
[G66.4,45.2Dustwallow Marsh]Set your hearth to [S Theramore]
[G59.6,41.2]Accept[QA7070]
[T]Train first aid if you need to, 240, 260, or 290[OC]
Fly to [F Ratchet]
Take the boat to Booty Bay[OC]
[G28.2,76.2Stranglethorn Vale]Turn in[QT836] if you did it[OC]
Turn in[QT2767] if you did it[OC]
[G27,77.4]Turn in[QT580]
Fly to [F Nethergarde Keep]
[G66.6,21.4Blasted Lands]Turn in[QT1395]
[G67,19]In the tower, turn in[QT2990]
Accept[QA2991]
Fly to [F Stormwind]
[T]Train your level 48 skills and visit the Auction House for the elixir of fortification if you need it[OC]
[H]Hearth to Theramore
Fly to [F Gadgetzan]
Start looking for a group for ZulFarak, ideally level 44+, but 43 is okay in a pinch[OC]
[G51.4,28.8Tanaris]Accept [QA3042]
[G51.8,28.6]Accept [QA2605]
[G52.4,28.4]Accept [QA2768]
[G53,27]Accept [QA5863]
[G52.4,27]Next to the gnome, if you got the Hippogryph egg, turn it in to the Egg-o-Matic machine[OC]
Accept [QA3022] from the gnome
[G50.2,27.4]Accept[QA992]
[G51.6,26.8]Accept[QA3362]
Accept[QA2865]
You should have all the quests for ZF in your quest log now, so do it whenever you can![OC]
On the way, kill any Rocs you see for their Gizzards[OC]
[G39,30]Use the Tapped Dowsing Widget near the water for [QC992]
On the way back to Gadgetzan, make sure you looted 3 gizzard for [QC1452,1]
[G50.2,27.4]Turn in[QT992]
Accept[QA82]
[G53,46]Turn in[QT3445]
Accept[QA3444]
Accept[QA3161]
[G35,46]Ride west and kill Silithid for [QC82]
[G29,65]Kill the elementals here for [QC3362]
Keep killing Dew Collectors for [QC2605] if you still haven't gotten the quest item drop yet
Look for mounds of sand to loot while doing the next step[OC]
[G40,73]Kill Dunemaul ogres while looting sand until you complete [QC3161]
[G41,57]Finish killing Ogres around the cave, then kill the named one inside for [QC5863]
Ride back to Gadgetzan[OC]
[G51.8,28.6]Turn in[QT2605]
Accept[QA2606]
[G51,26]Turn in[QT2606]
Accept[QA2641]
[G50.8,27]Turn in[QT82]
[G50.2,27.4]Accept[QA10]
[G51.6,26.8]Turn in[QT3362]
[G53,27]Turn in[QT5863]
[V]Sell your trash 
Ride south out of Gadgetzan[OC]
[G53,46]Turn in[QT3161]
Keep riding to south eastern Tanaris[OC]
[G54,71]Take the upper opening, head towards the large round room, proceed through the tunnel. Keep going and take another left, The machine is guarded by 1 insect. Loot it for [QC10]
[G60.2,64.4]You should have gotten the beacon by now for the chicken escort, turn in [QT351][OC]
Accept [QA648] if you're doing all of them[OC]
Complete the escort for [QC648]
Ride back to Gadgetzan[OC]
[G50.2,27.4]Turn in[QT10]
Accept[QA110]
[G50.8,27]Turn in[QT110]
Accept[QA113]
[G50.2,27.4]Turn in[QT113]
Accept[QA162]
Grind until level [XP49]
Bring the elixirs of fort with you for the next part[OC]
Ride north into the shimmering flats[OC]
[G78,74Thousand Needles]Turn in[QT3841]
Accept[QA3842]
Turn in[QT3842] if you have the elixirs[OC]
Accept[QA3843][OC]
[H]Hearth back to Theramore
[G59.6,41.2Dustwallow Marsh]If you don't have the quest, accept [QA7070]
[G46,57]If you did ZF, turn in[QT2846][OC]
If you did ZF, this guide will take you to turn in a couple quests, if you didn't do ZulFarak, take the boat to Menethil, then fly to Hinterlands and skip the next optional steps[OC]
Fly to Ratchet[OC]
Ride to Booty Bay[OC]
[G28.2,76.2Stranglethorn Vale]Turn in the chicken quests if you did them[OC]
Accept [QA3721][OC]
Turn in[QT3721][OC]
Fly to Nethergarde Keep[OC]
[G67,19Blasted Lands]Turn in[QT2991][OC]
Accept[QA2992][OC]
Wait a few seconds, then turn in[QT2992][OC]
Accept[QA2993][OC]
Fly to Aerie Peak[OC]
[G10,44.6The Hinterlands]Turn in[QT2993][OC]
[G14,43.2]Inside the keep, Turn in[QT3843][OC]
Accept[QA4297][OC]
IF YOU SKIPPED THE OPTIONAL STUFF, THIS IS WHERE YOU REJOIN THE GUIDE[OC]
[G26,48]Turn in[QT1452]
Accept[QA1469]
SKIP THE NEXT STEP IF YOU DO NOT HAVE THE QUEST 'FOOD FOR BABY'[OC]
Head east and kill stealth Silvermane Stalker for [QC4297][OC]
[G40,60]Loot the mushroom for [QC2641] DO NOT EAT THE MUSHROOM
[G14,43.2]Turn in[QT4297] if you did it [OC]
Accept[QA4298][OC]
Turn in[QT4298][OC]
[V]Sell your trash
Fly to [F Thorium Point]
[NX 49 - 51 Searing Gorge]
]],"Hakurai - by Shikushiku")