Guidelime.registerGuide(
[[
[N 33 - 36 STV]
[GA Alliance]
[D Made from Hakurai's Video Guide\\ https://twitch.tv/hakurai \\ Our guild is recruiting! \\ https://www.guilded.gg/KOABD]
Always grind mobs that give you xp in between locations, ALWAYS GRIND MOBS OR YOU WILL FALL BEHIND IN XP![OC]
Mail your herbs to your alt [OC]
[V]Clear bag space and buy enough Hot Spices at the Inn for 175 Cooking. Double howevery many skillups you need just in case.[OC]
[G45,66.8Duskwood]Head West along the road.
[G38,3.4Stranglethorn Vale]Head south into STV
Turn in[QT198]
Accept[QA215]
[G38,3.4]Accept[QA203]
Accept[QA204]
[G38,3]Accept[QA200]
[G37.8,3.2]Accept[QA210]
[G38,3][V]Buy any 10 slot bags you need
[G34.6,7.2]Near the river, kill basilisk to start working towards Singing Blue Shards[OC]
[G34.4,10.6]Kill Crocolisk and finish [QC575]
[G35.6,10.6]Accept[QA583]
Turn in at Hemet[QT583]
Accept[QA194]
Accept[QA190]
Accept[QA185]
Start collecting pages for Green Hills but don't accept the quest yet, just make sure you hold on to them[OC]
[G37.6,13.2]Kill tigers around the camp for [QC185]
[G35.6,10.6]Turn in[QT185]
Accept[QA186]
[G43,15]Work on Panthers in this area [QC186]
[G45,10.8]Head up the hill to kill Fighters for [QC203] while killing medicine men for [QC204,1]
[G47,17.8]Move south east for [QC186]
Tigers are okay to overkill, good vendor trash and level cooking[OC]
Farm an extra Jungle Potion for later[OC]
[G43.7,9.4]Before going inside the house, loot the crates for [QC204,2]
Might have to suicide run the next part, or group to clear multiple mobs inside the building[OC]
Inside the house and upstairs is the turn in for[QT200] 
Accept[QA328]
Grind on the tigers a little more if no one is killing them for level [XP33.9][OC]
[G35.6,10.6]Turn in[QT190]
Accept[QA191]
Turn in [QT186]
Accept[QA187]
[V]Vendor your trash drops, keep pages, herbs, and tiger meat. I mention tusks later, but those are just for warriors.
[G30.6,21]Work on killing Bloodscalp for ears and tusks, but don't worry about finishing them immediately[OC]
[G32.2,20]Kill Elder Tigers, kill as many as possible, don't worry about finishing immediately[OC]
[G29.8,11.2]Kill Panthers, kill as many as possible but don't worry about finishing immediately[OC]
[G27.6,17.4]Kill Raptors, kill as many as possible, you need their eggs for 175 cooking. Finish this quest now[QC194]
[G26.2,19.2]Kill Basilisk and try to finish [QC605]
[G21,21]Care for the elite crocolisk on the coast and water elementals. [QC578]
[G26.2,19.2]Kill Basilisk and try to finish [QC605] if you didn't.
[G27.6,17.4]Kill Raptors, kill as many as possible, Finish this quest now[QC194] and farm the rest of your eggs
[G29.8,11.2]Kill Panthers, try to finish this quest now[QC191]
[G32.2,20]Kill Elder Tigers, finish this quest now [QC187]
[G30.6,21]Work on killing Bloodscalp for ears and tusks, finish these quests now[QC189]
[G35.6,10.6]Turn in[QT187]
Accept[QA188]
Turn in[QT191]
Accept[QA192]
Turn in[QT194]
Accept[QA195]
[G38,3.4]Turn in[QT204]
Turn in[QT203]
[V]Clear trash, don't sell raptor flesh or tiger meat, keep the extra jungle potion.
Start by cooking the raptor eggs to hit 175 cooking, learn the turtle recipe from south shore. [OC]
[V]Buy the Jungle Stew Recipe from the vendor[OC]
Cook whatever you can and hold onto the food for now.
Make bandages to clear your bags.
[H]Hearth to Booty Bay[A Warlock,Priest,Rogue,Druid,Paladin,Hunter,Mage]
[G45,66.8Duskwood]Head West along the road.[A Warrior]
[G73.8,46.1]Walk back to Darkshire and mail your herbs[A Warrior]
[G77.6,44.4]Fly to [F Booty Bay][A Warrior]
[G27,77.2Stranglethorn Vale]Turn in[QT201] inside the inn
Turn in[QT210]
Accept[QA627]
[G27.2,76.8]Turn in[QT578]
Accept[QA601]
[G27,77.2]Downstairs, turn in[QT605]
Accept[QA600]
Turn in[QT189]
[G28.2,77.4]Turn in[QT575]
Accept[QA577]
[G27,77.2]Set Hearthstone to [S Booty Bay][A Warrior]
[G27.4,77.6]Fly to [F Darkshire]
If you're playing on a F R E S H server then drop Favor for Krazek, we wont be able to buy the ore[OC]
[G45,66.8Duskwood]Head West along the road.
[G35.6,10.6Stranglethorn Vale]Head south into STV
[G33,17.8]Kill SinDall for [QC188]
[G37.2,24.2]Kill Raptors for [QC195]
[G21.2,22]Kill Water Elementals for[QC601] try to avoid the level 37s but kill them if you have to.
[G30.6,21]Finish farming Ears if you didn't earlier [QC189]
[G30.6,21]Finish farming tusks for [QC1712,2][A Warrior]
[G35.6,10.6]Turn in[QT186]
Turn in[QT195]
Accept[QA196]
[V]Quickly vendor your garbage, and check if you have any greenhill chapters done to turn those in.
[G41.2,15.4]Start killing Crocolisks, but don't worry about finishing the quest yet.[OC]
You May need a group for this quest, it's hard to solo.[OC]
[G42,18]At the top of the platform, kill Foreman Cozzle and grab his key[OC]
[G43.4,20.4]Loot the chest for [QC1182]
[G43,21]Kill goblins in the area for [QC213]
Finish killing Crocolisks for [QC577]
[G49,23]THESE MOBS ARE STEALTH, kill panthers for [QC192]
[G35.6,10.6]Turn in[QT192]
Accept[QA193]
Turn in any chapters you can[OC]
[H]Hearth to Booty Bay
[G28.2,77.4]Turn in[QT577]
[G27,77.2]Turn in[QT189]if you didn't earlier[OC]
[G27,77.2]Turn in[QT213]
[G27.2,76.8]Turn in[QT601]
Accept[QA602]
Turn in[QT1182]
Accept[QA1183]
[G26.6,76.4]Bank any extra pages you still have
You can fly to Ironforge instead of Southshore if you want to train skills first[OC]
[G27.4,77.6]Fly to Southshore
[G51.2,58.8Hillsbrad Foothills]Set your hearth to [S Southshore]
[G50.2,58.8]Accept[QA659]
[G49.6,58.6]Accept[QA500]
[G48.2,59.4]Accept[QA505]
[G50.4,57]Accept[QA540]
[G52.4,56]Accept[QA564]
[G46,32]Enter the cave and loot the white stones for [QC689]
[G46,32]Exit the cave, and then head west around the mountain.
[G38.6,23.4]Up the hill, kill all the lions, if you can't finish it, we will loop back later.[OC]
[G56.4,64Alterac Mountains]Kill a few Syndicate for the quest
[G58.3,68.1]Accept the quest from the letter on the table[QA510]
Accept quest [QA511]
Finish killing mobs for [QC505]
[G50,58]Start killing Ogres for [QC500] care for the elites to the north of the road.
[G18.8,78.2]Grind Yetis to the west and herb on the way. Turn in[QT602]
Accept[QA603]
[G29.8,81.6]Finish killing Lions for[QC564]
[G38,68]Enter the ruins from the west, follow the ruins clock-wise, there's a hole in the wall directly west. 
[G38.5,46.4]You want to get as close as you can to here and then die, then ressurect behind the building. You can loot the item you need through the wall behind the building. Or just find a group and clear the normal way[QC540,2]
[H]Hearth back to Southshore
[V]Vendor trash at the inn and mail your herbs
[G49.6,58.6Hillsbrad Foothills]Turn in[QT500]
[G48.2,59.4]Turn in[QT505]
Turn in[QT510]
[G50.4,57]Turn in[QT540]
Turn in[QT511]
Accept[QA514]
Accept[QA542]
[G52.4,56]Turn in[QT564]
[V]Clear up bags, mail herbs to alt[OC]
[G49.4,52.4]Fly to [F Refuge Point]
During the flight log onto your alt to mail yourself back all the herbs you've been sending[OC]
[G46.2,47.6Arathi Highlands]Accept[QA691]
[G60.2,53.8]Turn in[QT659]
Accept[QA658]
The next quest is hard to solo, might want to group, there's 5 mobs that spawn with him[OC]
[G60.2,59]Wait for the Courier to spawn, don't bother chasing the road, just wait for him to spawn and kill mobs nearby[OC]
[G66,63]Kill Witherbark for Worth it's Weight in gold in the area.[QC691,1][QC691,2]
[G67.8,78.4]Shadow Hunters spawn south in the cave[QC691,3]
Gather as many herbs as possible on the way back.[OC]
[G60.2,59]Wait for the Courier to spawn if he didn't earlier, [QC658]
[G60.2,53.8]Turn in[QT658]
Accept[QA657]
Turn in[QT657] 
Accept[QA660]If she doesn't appear, someone else is doing the escort. Grind while waiting for respawn.
Finish [QC660]
[G60.2,53.8]Turn in[QT660]
Accept[QA661]
Grind to [XP36] or be 1 bar away[OC]
[G46.2,47.6]Turn in[QT691]
Fly to[F Southshore]
[G50.2,58.8Hillsbrad Foothills]Turn in[QT661]
If you are not a warrior fly to Ironforge[OC]
[G49.4,52.4]Fly to [F Menethil Harbor][A Warrior]
Mail 5g to your alt so you can send your herbs back, then log out, log into your alt, and mail all your herbs back[OC][A Warrior]
Take the boat to Auberdine[OC][A Warrior]
[G36.4,45.4Darkshore]Fly to [F Rut'theran Village][A Warrior]
Take the teleporter to Darnassus[OC][A Warrior]
[G39.6,42.4Darnassus]Clear as much space as possible for all your herbs, take out at least 70 peacebloom and silverleaf, and earthroot if you can[A Warrior]
[G41.4,42.2]Take all your herbs out of the mailbox[A Warrior]
[G56.2,24.2]Go to the alchemist trainer[OC][A Warrior]
Unlearn skinning[OC][A Warrior]
[T]Train Alchemy and buy a bunch of vials.[A Warrior]
Craft Minor Healing potions until 60 alchemy, KEEP THE POTIONS[OC][A Warrior]
[T]Train Journeyman Alchemy and Lesser Healing Potions[OC][A Warrior]
Grab Briarthorn from the mailbox if you didn't have space before[OC][A Warrior]
Make Lesser Healing Potions from 60-110, or mix and match skill ups if you don't have enough Briarthorn.[OC][A Warrior]
Make Healing potions from110-150, or whatever recipes you can throw together. Visit the AH if you have to[OC][A Warrior]
Keep 1 stack of healing potions for a quest later[OC][A Warrior]
[T]Train Expert Alchemy[OC][A Warrior]
Learn the Elixer of Ogre strength we farmed earlier and craft them from 150-190[OC][A Warrior]
When you hit 190 Learn the recipe for Nature Protection Potions, and make at LEAST 5, 10 if possible.[OC][A Warrior]
Afterwards dump the rest into Healing potions and Agility potions[OC][A Warrior]
[V]Vendor trash you don't need, but keep a stack of vials on you and level it when you can.[OC][A Warrior]
[G62,42.2][T]Train Whirlwind[A Warrior]
[H]Hearth back to Southshore[A Warrior]
Mail any excess potions or materials back to your alt, keep the nature protection and stack of healing potions[OC][A Warrior]
[G49.4,52.4Hillsbrad Foothills]Fly to [F Refuge Point][A Warrior]
[G52,51Arathi Highlands]Kill Thundering Exiles for 8 Charms[OC][A Warrior]
[G66,30]Kill Cresting Exiles for Charms[OC][A Warrior]
[V]Stop at Refuge point if you need to vendor[OC][A Warrior]
[G25,41]Kill Burning Exiles for Charms[OC][A Warrior]
MAKE SURE YOU HAVE 8 OF EACH CHARM, AND 8 LIFEROOT, AND YOUR TUSKS IN YOUR BAGS.[OC][A Warrior]
[H]Hearth to Southshore[OC][A Warrior]
[G79.4,66.7Alterac Mountains]Bring all your supplies and follow the river north to the troll ruins[OC][A Warrior]
Use the cauldron to turn in your charms for an essence[OC][A Warrior]
Turn in[QT1712][A Warrior]
Accept [QA1713][A Warrior]
Pop Nature Protection Potion, scrolls,food buffs, etc[OC][A Warrior]
Wait until Nature Protection is off cooldown before engaging[OC][A Warrior]
Loot his heart, turn in[QT1713] and take your nice new axe.[A Warrior]
Level your 2Handed axe skill,if you don't have it the next stop is Ironforge, either Hearth or walk back to the flight master, and fly to Ironforge.[OC][A Warrior]
[NX 36 - 37 Desolace]
]],"Hakurai - by Shikushiku")