local addonName, addon = ...
Guidelime.registerGuide([[
[D Night Elf Hunter guide for Classic Launch Mess\\by *Will Scarlett Ohara*]
[GANightElf]
[N6-12Teldrassil]
Accept [QA488 Zenn's Bidding]
Start doing [QC488 Zenn's Bidding][OC]
Collect and save 7xSmall Spider Leg for future quest[OC]
Turn in [QT928 Crown of the Earth part 2]
Accept [QA929 Crown of the Earth part 3]
Turn in [QT2159 Dolanaar Delivery]
[OC]Set [H]Hearth to Dolanaar and delete your hearthstone
[OC]Continue doing [QC488 Zenn's Bidding]
[OC][V Buy] 200 arrow and sell.[G55.89,59.2Teldrassil]
Accept [QA997 Denalan's Earth]
Accept [QA475 A Troubling Breeze]
Accept [QA932 Twisted Hatred]
Accept [QA2438 The Emerald Dreamcatcher]
[OC]Learn new spells[T][G56.64,59.39Teldrassil]
Do [QC929 Crown of the Earth part 3][G63,58.06Teldrassil]
Turn in [QT475 A Troubling Breeze]
Accept [QA476 Gnarlpine Corruption]
Do [QC2438 The Emerald Dreamcatcher]
[OC]Die with unstuck and spirit rez at Dolanaar.
Turn in [QT929 Crown of the Earth part 3]
Accept [QA933 Crown of the Earth part 4]
[OC][V]Sell.[G55.89,59.2Teldrassil]
Turn in [QT997 Denalan's Earth]
Accept [QA918 Timberling Seeds] and accept [QA919 Timberling Sprouts]
Do [QC918 Timberling Seeds] and do [QC919 Timberling Sprouts]
Turn in [QT918 Timberling Seeds] and turn in [QT919 Timberling Sprouts]
Accept [QA922 Rellian Greenspyre]
Do [QC488 Zenn's Bidding]
Turn in [QT488 Zenn's Bidding]
[T Train] Cooking [G57.12,61.29Teldrassil][OC]
Accept [QA4161 Recipe of the Kaldorei]
Do [QC4161 Recipe of the Kaldorei] Finish looting [QC4161,1 Small Spider Legs][OC]
Turn in [QT4161 Recipe of the Kaldorei]
[V Buy] 600 arrow and sell.[G55.89,59.2Teldrassil][OC]
Accept [QA489 Seek Redemption!]
Turn in [QT476 Gnarlpine Corruption]
Accept [QA483 The Relics of Wakening]
Learn [T] First Aid[G55.29,56.81Teldrassil][OC]
Go upstairs and [V Buy] one or two Small Brown Pouch if you not looted one and if you can afford it[G55.5,57.16Teldrassil][OC]
Turn in [QT2438 The Emerald Dreamcatcher] at the very top
Accept [QA2459 Ferocitas the Dream Eater]
You should be 8. Learn new spells.[T][OC]
Accept [QA487 The Road to Darnassus] if patrol is there
Do [QC932 Twisted Hatred]. Spawn location may vary inside the cave.
Accept [QA487 The Road to Darnassus]
Do [QC487 The Road to Darnassus] and do [QC489 Seek Redemption!] while your going to this fulborg camp.
Go to Ban'ethil Barrow Den [G44.38,57.86Teldrassil]
Do [QC483,2 The Relics of Wakening] and [QC483,4 The Relics of Wakening]
Accept [QA2541 The Sleeping Druid]
Do [QC2541 The Sleeping Druid], do  [QC483,3 The Relics of Wakening] and do [QC483,1 The Relics of Wakening]
Turn in [QT2541 The Sleeping Druid]
Accept [QA2561 Druid of the Claw]
Do [QC2561 Druid of the Claw] Use Voodoo Charm on [QC2561,1 Rageclaw] corpse.
Turn in [QT2561 Druid of the Claw]
Die with unstuck or use [H]hearthstone if you keeped it. Spirit Rezat at Dolanaar.[OC]
Sell you junk items[V] and [R repair][R][G55.89,59.2Teldrassil][OC]
[V Buy] arrows. Keep in mind you'll have new arrow on lvl10.[A Hunter][OC]
Turn in [QT483 The Relics of Wakening] and you should take the staff as reward. You'll use it later as a melee weapon.
Accept [QA486 Ursal the Mauler]
Turn in [QT489 Seek Redemption!]
Do [QC2459 Ferocitas the Dream Eater]. Right-click the necklace in your bag.
Die with unstuck and spirit Rezat at Dolanaar.[OC]
Sell you junk items[V] and [R repair][R][G55.89,59.2Teldrassil][OC]
[V Buy] on or two Small Brown Pouch if you not looted another one and if you can afford it at Aldia <General Supplies>[G55.5,57.16Teldrassil][OC]
Turn in [QT932 Twisted Hatred]
Turn in [QT2459 Ferocitas the Dream Eater]
Turn in [QT487 The Road to Darnassus]
Do [QC933 Crown of the Earth part 4][G42.43,67.35Teldrassil]
Accept [QA930 The Glowing Fruit] clic on the strange plant.
Do [QC486 Ursal the Mauler]
Go to east furbolg camp then die with unstuck. Important to go to the east side to rez at Dolanaar and not Darnassus. Spirit rez[OC]
Turn in [QT933 Crown of the Earth part 4]
Accept [QA7383 Crown of the Earth part 5]
Sell you junk items[V] and [R repair][R][G55.89,59.2Teldrassil][OC]
Turn in [QT486 Ursal the Mauler]
[V Buy] a skinning knife at Narret Shadowgrove<Trade Supplies> upstairs[G55.25,57.07Teldrassil].[OC]
Accept [QA6063 Taming the Beast][A NightElf,Hunter]
Learn new spells.[OC][T]
Do [QC6063 Taming the Beast] Go east[G59.3,59.49Teldrassil][A NightElf,Hunter]
Turn in [QT6063 Taming the Beast][A NightElf,Hunter]
Accept [QA6101 Taming the Beast part 2][A NightElf,Hunter]
Do [QC6101 Taming the Beast] Go south.[G56.42,72.46Teldrassil][A NightElf,Hunter] Dismiss your spider before taming the cat. You'll have to kill it.
Turn in [QT6101 Taming the Beast][A Hunter,NightElf]
Accept [QA6102 Taming the Beast]
Do [QC6102 Taming the Beast][A NightElf,Hunter][G44.02,51.03Teldrassil] Dismiss your cat before taming the owl. You'll have to kill it.
[OC][V Buy] new lvl10 arrows.[G55.88,59.17Teldrassil]
Turn in  [QT6102 Taming the Beast][A NightElf,Hunter]
Accept [QA6103 Training the Beast][A NightElf,Hunter]
Learn pet spells[OC]
Learn skinning[G42.1,49.97Teldrassil][T][OC]
Die there and spirit rez in Darnassus[OC]
[OC]Set [H]Hearth[G67.4,15.7Darnassus]
Turn in [QT6103 Training the Beast][A NightElf,Hunter]
Turn in [QT922 Rellian Greenspyre]
Accept [QA923 Tumors]
Accept [QA2519 The Temple of the Moon]
Turn in [QT2519 The Temple of the Moon]
Accept [QA2518 Tears of the Moon]
[V Buy] meat[OC][G64.78,69.4Darnassus] for you pet happyness. 20 should be fine. Tough Jerky is fine. Don't buy the lvl5 one.
Learn staves at weapon master[OC][G57.71,46.53Darnassus] It's 10 silvers.
Accept [QA6344 Nessa Shadowsong]
[OC]At this point try to kill and skin every cats you find and raise your skinning skills to 20 to be able to easily skin in Darkshore.
[OC]Tame a lvl9 owl. [G38.96,47.22Teldrassil]They have Claw Rank 2.[A Hunter]
Do [QC7383 Crown of the Earth part 5][G38.37,34.23Teldrassil]
Accept [QA937 The Enchanted Glade]
Do [QC937 The Enchanted Glade]
Accept [QA938 Mist]
Accept [QA931 The Shimmering Frond]
Do [QC938 Mist]
Turn in [QT937 The Enchanted Glade]
Turn in [QT938 Mist]
Accept [QA940 Teldrassil]
Do [QC938 Mist][G38.31,34.41Teldrassil]
Do [QC2518 Tears of the Moon] and do [QC923 Tumors]
[G49.13,55.8Teldrassil]Go south to die and spirit rez at Dolanaar.[OC]
Turn in [QT7383 Crown of the Earth part 5]
Accept [QA935 Crown of the Earth part 6]
[V Vendor] and [R Repair][OC]
Turn in [QT930 The Glowing Fruit]
Turn in [QT931]
[H] to Darnassus[OC]
Turn in [QT935 Crown of the Earth part 6]
Turn in [QT940 Teldrassil]
[T Train] spells if you are 12.[OC][G40.33,8.65Darnassus]
Accept [QA952 Grove of the Ancients]
Turn in [QT923 Tumors]
Skip [QS2498 Return to Denalan]
Turn in [QT2518 Tears of the Moon]
Accept [QA2520 Sathrah's Sacrifice]
Do [QC2520 Sathrah's Sacrifice]
Turn in [QT2520 Sathrah's Sacrifice]
[T Train] spells iff you are 12.[OC][G40.33,8.65Darnassus]
Go into floo network[G30.2,41.6Darnassus]
Turn in [QT6344 Nessa Shadowsong][G56.25,92.43Teldrassil]
Accept [QA6341 The Bounty of Teldrassil]
Turn in [QT6341 The Bounty of Teldrassil][G58.39,94Teldrassil]
Accept [QA6342 Flight to Auberdine]
Fly to [F Auberdine]
Turn in [QT6342 Flight to Auberdine]
Accept [QA6343 Return to Nessa]
Fly to [F Rut'theran Village, Teldrassil]
Turn in [QT6343 Return to Nessa]
Fly back to [F Auberdine]
Now, you're ready to follow a Darkshore guide or a Loch Modan one. If you do so, take the south boat on the docks to Menethil and run to[OC] Loch Modan. Have a nice Classic experience !
]],'Will Scarlett Ohara')